# 02 - Enriquecimiento externo

**Proyecto:** Siniestros fatales de tránsito en el Perú 2021-2025  
**Curso:** Agentes Inteligentes | Grupo 5

Este notebook toma el dataset limpio generado en el notebook 01 (`data/procesada/siniestros_limpio.csv`) y lo enriquece con fuentes oficiales reales.

El notebook 02 **no realiza feature engineering de modelado ni crea la variable objetivo**. Las variables derivadas temporales (`AÑO`, `MES`, `FRANJA_HORARIA`, `REGION_NATURAL`, `CATEGORIA_SEVERIDAD`, etc.) corresponden al notebook 03. Aquí solo se conserva la limpieza estricta del notebook 01 y se agregan variables externas/relacionales.

Fuentes integradas:

1. **Fuentes externas territoriales y viales:** MTC Red Vial Nacional, IDH PNUD/IPE e infraestructura vial departamental del MTC.
2. **Fuentes relacionales ONSV:** personas involucradas y vehículos involucrados, agregadas por `CODIGO_SINIESTRO`.

El resultado final se exporta como `data/procesada/siniestros_enriquecido.csv` y se documenta en `data/procesada/trazabilidad_variables_externas.csv`.

## 0. Configuración

El notebook está preparado para ejecutarse desde la raíz del repositorio o desde la carpeta `notebooks`. Todas las rutas son relativas al proyecto. Para evitar problemas al abrir los CSV en Excel, las salidas se escriben con `encoding="utf-8-sig"`.

In [1]:
from pathlib import Path
import re
import unicodedata
import warnings
import codecs

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

ROOT = Path.cwd().resolve()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent

DATA_RAW = ROOT / "data" / "raw"
DATA_EXT = ROOT / "data" / "externas"
DATA_PROC = ROOT / "data" / "procesada"
DATA_PROC.mkdir(parents=True, exist_ok=True)

PATHS = {
    "siniestros_limpio": DATA_PROC / "siniestros_limpio.csv",
    "personas_raw": DATA_RAW / "BBDD ONSV - PERSONAS 2021-2025 (preliminar) (1).xlsx",
    "vehiculos_raw": DATA_RAW / "BBDD ONSV - VEHICULOS 2021-2025 (preliminar) (1).xlsx",
    "mtc_rvn": DATA_EXT / "1_Red_vial_nacional_2022-2025.csv",
    "idh": DATA_EXT / "IDH-y-Componentes-2003-2019.xlsx",
    "mtc_departamento": DATA_EXT / "344790-red-vial-existente-del-sistema-nacional-de-carreteras-segun-departamento-2010-jun-2025.xlsx",
    "salida_enriquecido": DATA_PROC / "siniestros_enriquecido.csv",
    "salida_trazabilidad": DATA_PROC / "trazabilidad_variables_externas.csv",
}

print(f"ROOT detectado: {ROOT}")
print("\nVerificación de archivos de entrada:")
for nombre, ruta in PATHS.items():
    if nombre.startswith("salida"):
        continue
    print(f"{nombre:20s}: {'OK' if ruta.exists() else 'NO ENCONTRADO'} -> {ruta}")

ROOT detectado: /home/node-vault07/projects/siniestros-fatales-peru-ml

Verificación de archivos de entrada:
siniestros_limpio   : OK -> /home/node-vault07/projects/siniestros-fatales-peru-ml/data/procesada/siniestros_limpio.csv
personas_raw        : OK -> /home/node-vault07/projects/siniestros-fatales-peru-ml/data/raw/BBDD ONSV - PERSONAS 2021-2025 (preliminar) (1).xlsx
vehiculos_raw       : OK -> /home/node-vault07/projects/siniestros-fatales-peru-ml/data/raw/BBDD ONSV - VEHICULOS 2021-2025 (preliminar) (1).xlsx
mtc_rvn             : OK -> /home/node-vault07/projects/siniestros-fatales-peru-ml/data/externas/1_Red_vial_nacional_2022-2025.csv
idh                 : OK -> /home/node-vault07/projects/siniestros-fatales-peru-ml/data/externas/IDH-y-Componentes-2003-2019.xlsx
mtc_departamento    : OK -> /home/node-vault07/projects/siniestros-fatales-peru-ml/data/externas/344790-red-vial-existente-del-sistema-nacional-de-carreteras-segun-departamento-2010-jun-2025.xlsx

## 0.1 Mapa de tareas y failsafes del NB02

Esta celda deja explícito qué hace el notebook 02 y qué no debe hacer. El objetivo es evitar usar columnas que no existan en `siniestros_limpio.csv` y separar este paso del feature engineering del notebook 03.

Si una columna requerida del limpio no existe, el notebook debe fallar con un mensaje claro en lugar de asumirla o crearla manualmente.

In [2]:
TASKS_NB02 = pd.DataFrame([
    {
        "paso": 1,
        "tarea": "Cargar salida estricta del NB01",
        "entrada": "data/procesada/siniestros_limpio.csv",
        "failsafe": "Verificar existencia del archivo y lectura con utf-8-sig/utf-8/latin1.",
        "no_corresponde": "No crear variables derivadas ni target.",
    },
    {
        "paso": 2,
        "tarea": "Validar columnas requeridas del limpio",
        "entrada": "Columnas reales del CSV limpio",
        "failsafe": "Resolver columnas por alias normalizados; si falta una requerida, detener ejecución con KeyError explícito.",
        "no_corresponde": "No leer columnas que no estén en el CSV limpio ni hardcodear valores.",
    },
    {
        "paso": 3,
        "tarea": "Estandarizar llave primaria",
        "entrada": "CÓDIGO SINIESTRO",
        "failsafe": "Renombrar internamente a CODIGO_SINIESTRO y verificar 0 duplicados.",
        "no_corresponde": "No reconstruir IDs por orden de filas.",
    },
    {
        "paso": 4,
        "tarea": "Preparar llaves auxiliares de cruce",
        "entrada": "DEPARTAMENTO, PROVINCIA, DISTRITO, COD CARRETERA",
        "failsafe": "Crear solo llaves auxiliares temporales con prefijo _. Se eliminan antes de exportar.",
        "no_corresponde": "No exportar columnas auxiliares ni derivadas de modelado.",
    },
    {
        "paso": 5,
        "tarea": "Enriquecer con MTC e IDH",
        "entrada": "Fuentes en data/externas",
        "failsafe": "Usar validate='many_to_one', validar filas antes/después, duplicados y cobertura.",
        "no_corresponde": "No imputar para modelado; solo reportar nulos nuevos.",
    },
    {
        "paso": 6,
        "tarea": "Enriquecer con PERSONAS y VEHÍCULOS ONSV",
        "entrada": "Fuentes en data/raw agrupadas por CODIGO_SINIESTRO",
        "failsafe": "Agrupar a una fila por siniestro y usar validate='one_to_one'.",
        "no_corresponde": "No usar GRAVEDAD, lugar de atención/defunción ni conteos directos de fallecidos/lesionados.",
    },
    {
        "paso": 7,
        "tarea": "Exportar outputs del NB02",
        "entrada": "Base limpia + variables de enriquecimiento",
        "failsafe": "Validar filas, duplicados, columnas deprecadas ausentes y encoding utf-8-sig.",
        "no_corresponde": "No exportar AÑO, MES, FRANJA_HORARIA, REGION_NATURAL ni CATEGORIA_SEVERIDAD.",
    },
])

TASKS_NB02

,paso,tarea,entrada,failsafe,no_corresponde
0,1,Cargar salida estricta del NB01,data/procesada/siniestros_limpio.csv,Verificar existencia del archivo y lectura con...,No crear variables derivadas ni target.
1,2,Validar columnas requeridas del limpio,Columnas reales del CSV limpio,Resolver columnas por alias normalizados; si f...,No leer columnas que no estén en el CSV limpio...
2,3,Estandarizar llave primaria,CÓDIGO SINIESTRO,Renombrar internamente a CODIGO_SINIESTRO y ve...,No reconstruir IDs por orden de filas.
3,4,Preparar llaves auxiliares de cruce,"DEPARTAMENTO, PROVINCIA, DISTRITO, COD CARRETERA",Crear solo llaves auxiliares temporales con pr...,No exportar columnas auxiliares ni derivadas d...
4,5,Enriquecer con MTC e IDH,Fuentes en data/externas,"Usar validate='many_to_one', validar filas ant...",No imputar para modelado; solo reportar nulos ...
5,6,Enriquecer con PERSONAS y VEHÍCULOS ONSV,Fuentes en data/raw agrupadas por CODIGO_SINIE...,Agrupar a una fila por siniestro y usar valida...,"No usar GRAVEDAD, lugar de atención/defunción ..."
6,7,Exportar outputs del NB02,Base limpia + variables de enriquecimiento,"Validar filas, duplicados, columnas deprecadas...","No exportar AÑO, MES, FRANJA_HORARIA, REGION_N..."

In [3]:
def normalizar_texto(valor):
    """Normaliza texto para cruces: mayúsculas, sin tildes y sin espacios múltiples."""
    if pd.isna(valor):
        return ""
    texto = str(valor).strip().upper()
    texto = unicodedata.normalize("NFKD", texto).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"\s+", " ", texto)


def normalizar_codigo_ruta(valor):
    return normalizar_texto(valor).replace(" ", "")


def buscar_columna(df, nombre_objetivo):
    objetivo = normalizar_texto(nombre_objetivo)
    for col in df.columns:
        if normalizar_texto(col) == objetivo:
            return col
    for col in df.columns:
        if objetivo in normalizar_texto(col):
            return col
    raise KeyError(f"No se encontró la columna esperada: {nombre_objetivo}")


def leer_csv_seguro(path):
    for enc in ["utf-8-sig", "utf-8", "latin1"]:
        try:
            df_tmp = pd.read_csv(path, encoding=enc)
            print(f"Lectura CSV OK: {path.name} con encoding={enc}")
            return df_tmp, enc
        except UnicodeDecodeError:
            pass
    raise UnicodeDecodeError(f"No se pudo leer {path}")


def leer_excel_onsv(path, sheet_name):
    if not path.exists():
        raise FileNotFoundError(f"No existe el archivo: {path}")
    df_tmp = pd.read_excel(path, sheet_name=sheet_name, skiprows=4)
    df_tmp = df_tmp.dropna(how="all").copy()
    df_tmp.columns = [str(c).strip() for c in df_tmp.columns]
    return df_tmp


def moda_ponderada_por_longitud(grupo, col_valor, col_peso="LONGITUD"):
    tmp = grupo[[col_valor, col_peso]].dropna(subset=[col_valor]).copy()
    if tmp.empty:
        return np.nan
    tmp[col_peso] = pd.to_numeric(tmp[col_peso], errors="coerce").fillna(0)
    pesos = tmp.groupby(col_valor)[col_peso].sum().sort_values(ascending=False)
    if pesos.empty or pesos.iloc[0] == 0:
        modo = tmp[col_valor].mode()
        return modo.iloc[0] if not modo.empty else np.nan
    return pesos.index[0]


def reporte_nulos_nuevos(df_despues, cols_nuevas):
    disponibles = [c for c in cols_nuevas if c in df_despues.columns]
    if not disponibles:
        return pd.DataFrame(columns=["variable", "nulos", "nulos_pct"])
    tabla = df_despues[disponibles].isna().sum().rename("nulos").reset_index()
    tabla = tabla.rename(columns={"index": "variable"})
    tabla["nulos_pct"] = (tabla["nulos"] / len(df_despues) * 100).round(2)
    return tabla.sort_values("nulos_pct", ascending=False)


def validar_merge(df_antes, df_despues, nombre_fuente, cols_nuevas, llave=None):
    print("=" * 80)
    print(f"VALIDACIÓN POST-MERGE: {nombre_fuente}")
    print("=" * 80)
    print(f"Filas antes:   {len(df_antes):,}")
    print(f"Filas después: {len(df_despues):,}")
    assert len(df_antes) == len(df_despues), "El merge cambió la cantidad de filas."

    if llave and llave in df_despues.columns:
        duplicados = int(df_despues[llave].duplicated().sum())
        print(f"Duplicados en llave {llave}: {duplicados:,}")
        assert duplicados == 0, f"Se generaron duplicados en {llave}."

    if "CATEGORIA_SEVERIDAD" in df_antes.columns and "CATEGORIA_SEVERIDAD" in df_despues.columns:
        dist_antes = df_antes["CATEGORIA_SEVERIDAD"].value_counts(dropna=False).sort_index().to_dict()
        dist_despues = df_despues["CATEGORIA_SEVERIDAD"].value_counts(dropna=False).sort_index().to_dict()
        assert dist_antes == dist_despues, "Cambió la distribución de CATEGORIA_SEVERIDAD."
        print("Variable objetivo: inalterada")

    disponibles = [c for c in cols_nuevas if c in df_despues.columns]
    tiene_cruce = df_despues[disponibles].notna().any(axis=1) if disponibles else pd.Series(False, index=df_despues.index)
    cobertura = tiene_cruce.mean() * 100
    cruzados = int(tiene_cruce.sum())
    no_cruzados = len(df_despues) - cruzados
    print(f"Cobertura fuente: {cobertura:.2f}% ({cruzados:,} cruzados; {no_cruzados:,} no cruzados)")
    print(f"Columnas nuevas: {len(disponibles)}")
    nulos = reporte_nulos_nuevos(df_despues, disponibles)
    print("\n% de nulos en variables nuevas:")
    display(nulos)
    return cobertura, cruzados, no_cruzados, nulos


def agregar_trazabilidad(registros, variables, fuente, archivo_origen, url, llave_cruce, anio_dato, nivel_geografico, cobertura, cruzados, no_cruzados, observaciones):
    for variable in variables:
        registros.append({
            "variable": variable,
            "fuente": fuente,
            "archivo_origen": str(archivo_origen),
            "url_fuente": url,
            "llave_cruce": llave_cruce,
            "anio_dato": anio_dato,
            "nivel_geografico": nivel_geografico,
            "cobertura_pct": round(float(cobertura), 2),
            "registros_cruzados": int(cruzados),
            "registros_no_cruzados": int(no_cruzados),
            "observaciones": observaciones,
        })

## 1. Carga del dataset limpio y verificación de columnas

Se carga `siniestros_limpio.csv` desde `data/procesada`. Este archivo es la salida estricta de limpieza del notebook 01: conserva las columnas originales limpias y no debe incluir variables derivadas de modelado.

El notebook 02 valida las columnas necesarias mediante alias normalizados. Si una columna requerida no existe en el CSV limpio, el notebook se detiene con un error explícito. La única estandarización permanente de nombre es `CÓDIGO SINIESTRO` a `CODIGO_SINIESTRO`, porque esa llave se usa para cotejar merges con PERSONAS y VEHÍCULOS de ONSV.

In [4]:
if not PATHS["siniestros_limpio"].exists():
    raise FileNotFoundError(f"No se encontró el dataset limpio: {PATHS['siniestros_limpio']}")

df, encoding_entrada = leer_csv_seguro(PATHS["siniestros_limpio"])
filas_originales = len(df)
columnas_limpio_originales = list(df.columns)

# Resolver columnas del limpio por alias, no por posición ni por nombre exacto.
# Esto evita que el notebook falle si el NB01 cambia tildes, espacios o nombres equivalentes.
COLUMN_ALIASES = {
    "CODIGO_SINIESTRO": ["CODIGO SINIESTRO", "CÓDIGO SINIESTRO", "COD SINIESTRO", "ID SINIESTRO"],
    "FECHA SINIESTRO": ["FECHA SINIESTRO", "FECHA", "FECHA DEL SINIESTRO"],
    "HORA SINIESTRO": ["HORA SINIESTRO", "HORA", "HORA DEL SINIESTRO"],
    "CANTIDAD DE FALLECIDOS": ["CANTIDAD DE FALLECIDOS", "FALLECIDOS", "N FALLECIDOS", "NUMERO DE FALLECIDOS"],
    "CANTIDAD DE LESIONADOS": ["CANTIDAD DE LESIONADOS", "LESIONADOS", "N LESIONADOS", "NUMERO DE LESIONADOS"],
    "DEPARTAMENTO": ["DEPARTAMENTO", "DPTO", "REGION"],
    "PROVINCIA": ["PROVINCIA"],
    "DISTRITO": ["DISTRITO"],
    "COD CARRETERA": ["COD CARRETERA", "CODIGO CARRETERA", "CÓDIGO CARRETERA", "CODIGO DE CARRETERA"],
    "RED VIAL": ["RED VIAL", "TIPO RED VIAL"],
}

columnas_resueltas = {}
for canonica, alias in COLUMN_ALIASES.items():
    for candidato in alias:
        try:
            columnas_resueltas[canonica] = buscar_columna(df, candidato)
            break
        except KeyError:
            continue

requeridas = [
    "CODIGO_SINIESTRO", "CANTIDAD DE FALLECIDOS", "CANTIDAD DE LESIONADOS",
    "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "COD CARRETERA", "RED VIAL",
]
faltantes = [c for c in requeridas if c not in columnas_resueltas]
if faltantes:
    raise KeyError(
        "Faltan columnas requeridas en siniestros_limpio.csv: "
        f"{faltantes}. Columnas disponibles: {list(df.columns)}"
    )

# Estandarizar solo columnas necesarias para que el resto del pipeline use nombres canónicos.
renombrar = {
    origen: canonica
    for canonica, origen in columnas_resueltas.items()
    if origen in df.columns and origen != canonica
}
df = df.rename(columns=renombrar)
df["CODIGO_SINIESTRO"] = df["CODIGO_SINIESTRO"].astype(str)

duplicados_iniciales = int(df["CODIGO_SINIESTRO"].duplicated().sum())
assert duplicados_iniciales == 0, "El dataset limpio tiene CODIGO_SINIESTRO duplicado."

print(f"Archivo base: {PATHS['siniestros_limpio']}")
print(f"Encoding usado: {encoding_entrada}")
print(f"Dataset limpio original: {filas_originales:,} filas x {len(columnas_limpio_originales)} columnas")
print(f"Columnas estandarizadas para el pipeline: {len(renombrar)}")
print(f"Duplicados en CODIGO_SINIESTRO: {duplicados_iniciales:,}")
print("\nMapa de columnas usadas:")
display(pd.DataFrame(
    [{"columna_canonica": k, "columna_detectada": v} for k, v in columnas_resueltas.items()]
))
df.head()

Lectura CSV OK: siniestros_limpio.csv con encoding=utf-8-sig
Archivo base: /home/node-vault07/projects/siniestros-fatales-peru-ml/data/procesada/siniestros_limpio.csv
Encoding usado: utf-8-sig
Dataset limpio original: 9,106 filas x 27 columnas
Columnas estandarizadas para el pipeline: 1
Duplicados en CODIGO_SINIESTRO: 0

Mapa de columnas usadas:

         columna_canonica       columna_detectada
0        CODIGO_SINIESTRO        CÓDIGO SINIESTRO
1         FECHA SINIESTRO         FECHA SINIESTRO
2          HORA SINIESTRO          HORA SINIESTRO
3  CANTIDAD DE FALLECIDOS  CANTIDAD DE FALLECIDOS
4  CANTIDAD DE LESIONADOS  CANTIDAD DE LESIONADOS
5            DEPARTAMENTO            DEPARTAMENTO
6               PROVINCIA               PROVINCIA
7                DISTRITO                DISTRITO
8           COD CARRETERA           COD CARRETERA
9                RED VIAL                RED VIAL

,CODIGO_SINIESTRO,FECHA SINIESTRO,HORA SINIESTRO,CLASE SINIESTRO,CANTIDAD DE FALLECIDOS,CANTIDAD DE LESIONADOS,CANTIDAD DE VEHICULOS DAÑADOS,DEPARTAMENTO,PROVINCIA,DISTRITO,...,ZONIFICACIÓN,CARACTERÍSTICAS DE VÍA,PERFIL LONGITUDINAL VÍA,SUPERFICIE DE CALZADA,¿EXISTE SEÑAL VERTICAL?,CLASIFICACIÓN DE LA SEÑAL VERTICAL Nº 1,CLASIFICACIÓN DE LA SEÑAL VERTICAL Nº 2,¿EXISTE SEÑAL HORIZONTAL?,CAUSA FACTOR PRINCIPAL,CAUSA ESPECÍFICA
0,A-2021-01-23,01/01/2021,04:40,DESPISTE,1,0,1,LIMA,HUARAL,HUARAL,...,RURAL,TRAMO RECTO,PLANA,TROCHA,SIN_DATO,SIN_DATO,SIN_DATO,SIN_DATO,EN PROCESO DE INVESTIGACIÓN,NO CUENTA CON CAUSA ESPECIFICA
1,A-2021-01-248,01/01/2021,05:45,DESPISTE,1,3,0,LIMA,LIMA,PACHACAMAC,...,INDUSTRIAL,TRAMO RECTO,PLANA,ASFALTADA,SIN_DATO,SIN_DATO,SIN_DATO,SIN_DATO,IMPRUDENCIA DEL CONDUCTOR,CONDUCIR EN ESTADO DE EBRIEDAD Y/O DROGADICCIÓN
2,A-2021-01-38,01/01/2021,06:00,ATROPELLO FUGA,2,0,1,LA LIBERTAD,VIRU,VIRU,...,COMERCIAL,TRAMO RECTO,PLANA,ASFALTADA,SIN_DATO,SIN_DATO,SIN_DATO,SIN_DATO,EN PROCESO DE INVESTIGACIÓN,NO CUENTA CON CAUSA ESPECIFICA
3,A-2021-01-39,01/01/2021,07:00,CHOQUE,1,0,2,LA LIBERTAD,VIRU,VIRU,...,RURAL,TRAMO RECTO,PLANA,ASFALTADA,SIN_DATO,SIN_DATO,SIN_DATO,SIN_DATO,IMPRUDENCIA DEL CONDUCTOR,GIRAR IMPRUDENTEMENTE
4,A-2021-01-254,01/01/2021,14:00,ATROPELLO,1,1,0,LIMA,LIMA,VILLA MARIA DEL TRIUNFO,...,INDUSTRIAL,TRAMO RECTO,PLANA,ASFALTADA,SIN_DATO,SIN_DATO,SIN_DATO,SIN_DATO,IMPRUDENCIA DEL CONDUCTOR,CONDUCIR EN ESTADO DE EBRIEDAD Y/O DROGADICCIÓN

In [5]:
# NB02 no crea variables derivadas ni target.
# Esa etapa pertenece al NB03. Aquí se conserva la estructura limpia del NB01.
df_original = df.copy()
cols_originales = list(df_original.columns)
columnas_derivadas_no_permitidas = [
    "AÑO", "MES", "DIA_SEMANA", "ES_FIN_SEMANA", "HORA_NUM", "FRANJA_HORARIA",
    "REGION_NATURAL", "CATEGORIA_SEVERIDAD", "MORTALIDAD_MULTIPLE", "LESION_MULTIPLE",
]
presentes_no_permitidas = [c for c in columnas_derivadas_no_permitidas if c in df.columns]
assert not presentes_no_permitidas, (
    "El dataset limpio contiene columnas derivadas que deben generarse en NB03, no en NB02: "
    f"{presentes_no_permitidas}"
)

print(f"Dataset base para enriquecimiento: {df.shape[0]:,} filas x {df.shape[1]} columnas")
print(f"Columnas del limpio original: {len(columnas_limpio_originales)}")
print("NB02 no crea variables derivadas ni variable objetivo; solo agrega enriquecimientos.")
print("\nPrimeras columnas de la base limpia:")
print(df.columns.tolist()[:12])

Dataset base para enriquecimiento: 9,106 filas x 27 columnas
Columnas del limpio original: 27
NB02 no crea variables derivadas ni variable objetivo; solo agrega enriquecimientos.

Primeras columnas de la base limpia:
['CODIGO_SINIESTRO', 'FECHA SINIESTRO', 'HORA SINIESTRO', 'CLASE SINIESTRO', 'CANTIDAD DE FALLECIDOS', 'CANTIDAD DE LESIONADOS', 'CANTIDAD DE VEHICULOS DAÑADOS', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'ZONA', 'TIPO DE VÍA']

In [6]:
df["_DEP_NORM"] = df["DEPARTAMENTO"].apply(normalizar_texto)
df["_PROV_NORM"] = df["PROVINCIA"].apply(normalizar_texto)
df["_DIST_NORM"] = df["DISTRITO"].apply(normalizar_texto)
df["_COD_CARRETERA_NORM"] = df["COD CARRETERA"].apply(normalizar_codigo_ruta)

print(df[["CODIGO_SINIESTRO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "COD CARRETERA", "_COD_CARRETERA_NORM"]].head())

  CODIGO_SINIESTRO DEPARTAMENTO PROVINCIA                 DISTRITO  \
0     A-2021-01-23         LIMA    HUARAL                   HUARAL
1    A-2021-01-248         LIMA      LIMA               PACHACAMAC
2     A-2021-01-38  LA LIBERTAD      VIRU                     VIRU
3     A-2021-01-39  LA LIBERTAD      VIRU                     VIRU
4    A-2021-01-254         LIMA      LIMA  VILLA MARIA DEL TRIUNFO

    COD CARRETERA _COD_CARRETERA_NORM
0          LM-671              LM-671
1  NO CORRESPONDE       NOCORRESPONDE
2         LI-1150             LI-1150
3           PE-1N               PE-1N
4  NO CORRESPONDE       NOCORRESPONDE

## 2. Fuente MTC: Red Vial Nacional 2022-2025

**Relación con el problema:** las características de infraestructura vial pueden influir en la severidad del siniestro.

**Llave de cruce:** `COD CARRETERA` del ONSV contra `CODIGO_RUTA` del MTC. La cobertura no necesariamente es 100% porque el dataset incluye vías urbanas, vías sin clasificación o registros con `NO CORRESPONDE`.

In [7]:
mtc = pd.read_csv(PATHS["mtc_rvn"], encoding="latin1", sep=None, engine="python")
print(f"MTC Red Vial Nacional: {mtc.shape[0]:,} filas x {mtc.shape[1]} columnas")
print(mtc.columns.tolist())
mtc.head(3)

MTC Red Vial Nacional: 34,761 filas x 21 columnas
['ID_RVN', 'ID_DEPARTAMENTO', 'DEPARTAMENTO', 'CODIGO_RUTA', 'TRAYECTORIA', 'INICIO', 'FINAL', 'CLASIFICACION_EJE', 'JERARQUIA', 'LONGITUD', 'NRO_CARRILES', 'SUPERFICIE', 'SUPERFICIE_L', 'ESTADO', 'ESTADO_L', 'CODIGO_CONCESION', 'NOMBRE_CONCESION', 'CODIGO_LOGISTICO', 'CORREDOR_LOGISTICO', 'FECHA_CORTE', 'ES_CONCES']

,ID_RVN,ID_DEPARTAMENTO,DEPARTAMENTO,CODIGO_RUTA,TRAYECTORIA,INICIO,FINAL,CLASIFICACION_EJE,JERARQUIA,LONGITUD,...,SUPERFICIE,SUPERFICIE_L,ESTADO,ESTADO_L,CODIGO_CONCESION,NOMBRE_CONCESION,CODIGO_LOGISTICO,CORREDOR_LOGISTICO,FECHA_CORTE,ES_CONCES
0,1,20,PIURA,PE-02,Emp. PE-1N (Dv. Paita) - Paita,0.000,7.918,Transversal,RN,7.918,...,1,Pavimentado,1,Bueno,2,Eje Multimodal Amazonas Norte,C02,CO 2: Paita - Piura- Dv. Olmos,20221231,1
1,2,20,PIURA,PE-02,Emp. PE-1N (Dv. Paita) - Paita,7.918,40.095,Transversal,RN,32.177,...,1,Pavimentado,1,Bueno,2,Eje Multimodal Amazonas Norte,C02,CO 2: Paita - Piura- Dv. Olmos,20221231,1
2,3,20,PIURA,PE-02,Emp. PE-1N (Dv. Paita) - Paita,40.095,49.058,Transversal,RN,8.963,...,1,Pavimentado,1,Bueno,2,Eje Multimodal Amazonas Norte,C02,CO 2: Paita - Piura- Dv. Olmos,20221231,1

In [8]:
mtc = mtc.copy()
mtc["_COD_RUTA_NORM"] = mtc["CODIGO_RUTA"].apply(normalizar_codigo_ruta)
mtc["LONGITUD"] = pd.to_numeric(mtc["LONGITUD"], errors="coerce")
mtc["NRO_CARRILES"] = pd.to_numeric(mtc["NRO_CARRILES"], errors="coerce")
mtc["ES_CONCES"] = pd.to_numeric(mtc["ES_CONCES"], errors="coerce")

mtc_agg = (
    mtc.groupby("_COD_RUTA_NORM", dropna=False)
    .apply(lambda g: pd.Series({
        "MTC_RVN_LONGITUD_KM": g["LONGITUD"].sum(min_count=1),
        "MTC_RVN_N_CARRILES_MEDIANA": g["NRO_CARRILES"].median(),
        "MTC_RVN_SUPERFICIE_DOMINANTE": moda_ponderada_por_longitud(g, "SUPERFICIE_L"),
        "MTC_RVN_ESTADO_DOMINANTE": moda_ponderada_por_longitud(g, "ESTADO_L"),
        "MTC_RVN_ES_CONCESIONADA": int((g["ES_CONCES"].fillna(0) > 0).any()),
        "MTC_RVN_CONCESION_PRINCIPAL": moda_ponderada_por_longitud(g, "NOMBRE_CONCESION"),
        "MTC_RVN_CORREDOR_LOGISTICO": moda_ponderada_por_longitud(g, "CORREDOR_LOGISTICO"),
        "MTC_RVN_N_TRAMOS": len(g),
    }))
    .reset_index()
)

for col in ["MTC_RVN_CONCESION_PRINCIPAL", "MTC_RVN_CORREDOR_LOGISTICO"]:
    mtc_agg[col] = mtc_agg[col].replace({"": np.nan, " ": np.nan})

assert mtc_agg["_COD_RUTA_NORM"].duplicated().sum() == 0, "MTC agregado tiene llaves duplicadas."
cols_mtc_rvn = [c for c in mtc_agg.columns if c.startswith("MTC_RVN_")]
print(f"Rutas MTC agregadas: {mtc_agg.shape[0]:,}")
mtc_agg.head()

Rutas MTC agregadas: 160

,_COD_RUTA_NORM,MTC_RVN_LONGITUD_KM,MTC_RVN_N_CARRILES_MEDIANA,MTC_RVN_SUPERFICIE_DOMINANTE,MTC_RVN_ESTADO_DOMINANTE,MTC_RVN_ES_CONCESIONADA,MTC_RVN_CONCESION_PRINCIPAL,MTC_RVN_CORREDOR_LOGISTICO,MTC_RVN_N_TRAMOS
0,PE-02,245.290,2.0,Pavimentado,Bueno,1,Eje Multimodal Amazonas Norte,Corredor IIRSA Norte,18
1,PE-02A,722.900,2.0,Asfaltado económico,Bueno,1,Emp.PE-1B-Buenos Aires - Canchaque,No corresponde,123
2,PE-02B,642.004,1.0,Asfaltado económico,Regular,0,No concesionado,No corresponde,108
3,PE-02C,35.985,-1.0,Pavimentado,Regular,0,No concesionado,No corresponde,25
4,PE-02E,22.413,-1.0,Afirmado,Regular,0,No concesionado,No corresponde,15

In [9]:
df_antes = df.copy()
df = df.merge(mtc_agg, left_on="_COD_CARRETERA_NORM", right_on="_COD_RUTA_NORM", how="left", validate="many_to_one")
df = df.drop(columns=["_COD_RUTA_NORM"], errors="ignore")

cov_mtc_rvn, cruz_mtc_rvn, no_mtc_rvn, nulos_mtc_rvn = validar_merge(
    df_antes, df, "MTC Red Vial Nacional 2022-2025", cols_mtc_rvn, llave="CODIGO_SINIESTRO"
)

print("\nEjemplos sin cruce MTC RVN:")
df.loc[~df[cols_mtc_rvn].notna().any(axis=1), ["COD CARRETERA", "RED VIAL", "DEPARTAMENTO"]].drop_duplicates().head(10)

================================================================================
VALIDACIÓN POST-MERGE: MTC Red Vial Nacional 2022-2025
================================================================================
Filas antes:   9,106
Filas después: 9,106
Duplicados en llave CODIGO_SINIESTRO: 0
Cobertura fuente: 55.04% (5,012 cruzados; 4,094 no cruzados)
Columnas nuevas: 8

% de nulos en variables nuevas:

                       variable  nulos  nulos_pct
0           MTC_RVN_LONGITUD_KM   4094      44.96
1    MTC_RVN_N_CARRILES_MEDIANA   4094      44.96
2  MTC_RVN_SUPERFICIE_DOMINANTE   4094      44.96
3      MTC_RVN_ESTADO_DOMINANTE   4094      44.96
4       MTC_RVN_ES_CONCESIONADA   4094      44.96
5   MTC_RVN_CONCESION_PRINCIPAL   4094      44.96
6    MTC_RVN_CORREDOR_LOGISTICO   4094      44.96
7              MTC_RVN_N_TRAMOS   4094      44.96

Ejemplos sin cruce MTC RVN:

     COD CARRETERA        RED VIAL DEPARTAMENTO
0           LM-671      PROVINCIAL         LIMA
1   NO CORRESPONDE          URBANO         LIMA
2          LI-1150      PROVINCIAL  LA LIBERTAD
5   NO CORRESPONDE          URBANO   SAN MARTIN
7   NO CORRESPONDE          URBANO        PIURA
10  NO CORRESPONDE          URBANO       ANCASH
11          PI-102   DEPARTAMENTAL        PIURA
18          PI-897      PROVINCIAL        PIURA
21  SIN CLASIFICAR  SIN CLASIFICAR        CUSCO
22          PU-152   DEPARTAMENTAL         PUNO

## 3. Fuente IDH PNUD/IPE 2019

**Relación con el problema:** el IDH y sus componentes funcionan como variables de contexto territorial.

**Llave de cruce:** `DEPARTAMENTO + PROVINCIA + DISTRITO`.

In [10]:
idh_raw = pd.read_excel(PATHS["idh"], sheet_name="IDH 2019", header=None)
print(f"IDH raw: {idh_raw.shape[0]:,} filas x {idh_raw.shape[1]} columnas")
idh_raw.head(15)

IDH raw: 2,305 filas x 17 columnas

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,índice de Desarrollo Humano 2019,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Valores normalizados,NaN,NaN,NaN,NaN,Índice de desarrollo Humano (IDH)
3,UBIGEO,DEPARTAMENTO,NaN,NaN,NaN,Población,Esperanza de vida al nacer,Población (18 años) con Educ. secundaria completa,Años de educación (Poblac. 25 y más),Ingreso familiar per cápita,NaN,Esperanza de vida al nacer,Población (18 años) con Educ. secundaria completa,Años de educación (Poblac. 25 y más),Logro educativo,Ingreso familiar per cápita,NaN
4,NaN,NaN,Provincia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,Distrito,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,000000,PERÚ,NaN,NaN,NaN,31296142.413458,75.422882,67.665801,9.135085,1032.160379,NaN,0.840381,0.676658,0.516555,0.591212,0.404528,0.585764
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,010000,AMAZONAS,NaN,NaN,NaN,397468.581272,68.947284,45.478122,6.4684,669.454132,NaN,0.732455,0.454781,0.328761,0.386671,0.257385,0.417736
11,010100,NaN,Chachapoyas,NaN,NaN,55806.768737,72.316707,67.043483,8.187815,944.577068,NaN,0.788612,0.670435,0.449846,0.549174,0.368997,0.542665
12,010101,1,Chachapoyas,NaN,NaN,33038.252677,72.192674,79.562705,10.018339,1259.130244,NaN,0.786545,0.795627,0.578756,0.678582,0.496605,0.642361
13,010102,2,Asuncion,NaN,NaN,267.447537,71.364553,71.006832,6.013571,561.102634,NaN,0.772743,0.710068,0.29673,0.459019,0.213429,0.423032
14,010103,3,Balsas,NaN,NaN,1467.034261,68.594405,32.772384,5.193542,415.021047,NaN,0.726573,0.327724,0.238982,0.279857,0.154167,0.315308

In [11]:
idh = idh_raw.iloc[8:, [0, 1, 2, 5, 6, 7, 8, 9, 16]].copy()
idh.columns = [
    "UBIGEO", "NIVEL_O_DEP", "NOMBRE", "IDH_POBLACION_2019", "IDH_ESP_VIDA_2019",
    "IDH_EDUC_SECUND_PCT_2019", "IDH_ANIOS_EDUC_2019", "IDH_INGRESO_PERCAP_2019", "IDH_2019",
]
idh = idh.dropna(subset=["UBIGEO"]).copy()
idh["UBIGEO"] = pd.to_numeric(idh["UBIGEO"], errors="coerce").astype("Int64").astype(str).str.zfill(6)

for col in ["IDH_POBLACION_2019", "IDH_ESP_VIDA_2019", "IDH_EDUC_SECUND_PCT_2019", "IDH_ANIOS_EDUC_2019", "IDH_INGRESO_PERCAP_2019", "IDH_2019"]:
    idh[col] = pd.to_numeric(idh[col], errors="coerce")

idh["TIPO_NIVEL"] = np.select(
    [idh["UBIGEO"].str.endswith("0000"), idh["UBIGEO"].str.endswith("00")],
    ["DEPARTAMENTO", "PROVINCIA"],
    default="DISTRITO",
)
idh["DEPARTAMENTO_IDH"] = np.where(idh["TIPO_NIVEL"].eq("DEPARTAMENTO"), idh["NIVEL_O_DEP"], np.nan)
idh["DEPARTAMENTO_IDH"] = idh["DEPARTAMENTO_IDH"].ffill()
idh["PROVINCIA_IDH"] = np.where(idh["TIPO_NIVEL"].eq("PROVINCIA"), idh["NOMBRE"], np.nan)
idh["PROVINCIA_IDH"] = idh["PROVINCIA_IDH"].ffill()
idh["DISTRITO_IDH"] = np.where(idh["TIPO_NIVEL"].eq("DISTRITO"), idh["NOMBRE"], np.nan)

idh_dist = idh[idh["TIPO_NIVEL"].eq("DISTRITO")].copy()
idh_dist["_DEP_NORM"] = idh_dist["DEPARTAMENTO_IDH"].apply(normalizar_texto)
idh_dist["_PROV_NORM"] = idh_dist["PROVINCIA_IDH"].apply(normalizar_texto)
idh_dist["_DIST_NORM"] = idh_dist["DISTRITO_IDH"].apply(normalizar_texto)

cols_idh = [
    "IDH_2019", "IDH_ESP_VIDA_2019", "IDH_EDUC_SECUND_PCT_2019",
    "IDH_ANIOS_EDUC_2019", "IDH_INGRESO_PERCAP_2019", "IDH_POBLACION_2019",
]
cols_idh_merge = ["IDH_UBIGEO"] + cols_idh
idh_dist_sel = idh_dist[["_DEP_NORM", "_PROV_NORM", "_DIST_NORM", "UBIGEO"] + cols_idh].drop_duplicates(["_DEP_NORM", "_PROV_NORM", "_DIST_NORM"])
idh_dist_sel = idh_dist_sel.rename(columns={"UBIGEO": "IDH_UBIGEO"})

assert idh_dist_sel[["_DEP_NORM", "_PROV_NORM", "_DIST_NORM"]].duplicated().sum() == 0, "IDH tiene llaves duplicadas."
print(f"Distritos IDH 2019 disponibles: {idh_dist_sel.shape[0]:,}")
idh_dist_sel.head()

Distritos IDH 2019 disponibles: 1,876

,_DEP_NORM,_PROV_NORM,_DIST_NORM,IDH_UBIGEO,IDH_2019,IDH_ESP_VIDA_2019,IDH_EDUC_SECUND_PCT_2019,IDH_ANIOS_EDUC_2019,IDH_INGRESO_PERCAP_2019,IDH_POBLACION_2019
12,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,010101,0.642361,72.192674,79.562705,10.018339,1259.130244,33038.252677
13,AMAZONAS,CHACHAPOYAS,ASUNCION,010102,0.423032,71.364553,71.006832,6.013571,561.102634,267.447537
14,AMAZONAS,CHACHAPOYAS,BALSAS,010103,0.315308,68.594405,32.772384,5.193542,415.021047,1467.034261
15,AMAZONAS,CHACHAPOYAS,CHETO,010104,0.345746,77.528252,52.210906,4.584966,398.663339,584.745182
16,AMAZONAS,CHACHAPOYAS,CHILIQUIN,010105,0.275038,72.460151,36.868932,3.712853,325.930531,390.717345

In [12]:
df_antes = df.copy()
df = df.merge(idh_dist_sel, on=["_DEP_NORM", "_PROV_NORM", "_DIST_NORM"], how="left", validate="many_to_one")
cov_idh, cruz_idh, no_idh, nulos_idh = validar_merge(
    df_antes, df, "IDH PNUD/IPE 2019 distrital", cols_idh_merge, llave="CODIGO_SINIESTRO"
)

print("\nEjemplos sin cruce IDH:")
df.loc[df["IDH_2019"].isna(), ["DEPARTAMENTO", "PROVINCIA", "DISTRITO"]].drop_duplicates().head(15)

================================================================================
VALIDACIÓN POST-MERGE: IDH PNUD/IPE 2019 distrital
================================================================================
Filas antes:   9,106
Filas después: 9,106
Duplicados en llave CODIGO_SINIESTRO: 0
Cobertura fuente: 96.91% (8,825 cruzados; 281 no cruzados)
Columnas nuevas: 7

% de nulos en variables nuevas:

                   variable  nulos  nulos_pct
0                IDH_UBIGEO    281       3.09
1                  IDH_2019    281       3.09
2         IDH_ESP_VIDA_2019    281       3.09
3  IDH_EDUC_SECUND_PCT_2019    281       3.09
4       IDH_ANIOS_EDUC_2019    281       3.09
5   IDH_INGRESO_PERCAP_2019    281       3.09
6        IDH_POBLACION_2019    281       3.09

Ejemplos sin cruce IDH:

    DEPARTAMENTO               PROVINCIA                              DISTRITO
53           ICA                   NASCA                               MARCONA
75         PASCO  DANIEL ALCIDES CARRION                                 TAPUC
80        CALLAO                  CALLAO                              LA PERLA
85        CALLAO                  CALLAO                                CALLAO
109        TACNA                   TACNA  CORONEL GREGORIO ALBARRACIN LANCHIPA
122       CALLAO                  CALLAO                            VENTANILLA
166      HUANUCO           LEONCIO PRADO                 SANTO DOMINGO DE ANDA
247          ICA                   NASCA                          VISTA ALEGRE
274      HUANUCO                 HUANUCO                      QUISQUI (KICHKI)
404         LIMA                    LIMA                          PUEBLO LIBRE
527         PUNO                  SANDIA             SAN PEDRO DE PUTINA PUNCO
541          ICA                   NASCA                            EL INGENIO
622     APURIMAC             ANDAHUAYLAS                   JOSE MARIA ARGUEDAS
629       CALLAO                  CALLAO                               MI PERU
681       CALLAO                  CALLAO            CARMEN DE LA LEGUA REYNOSO

## 4. Fuente MTC: infraestructura vial por departamento 2025

**Relación con el problema:** esta fuente agrega contexto vial departamental: longitud total de red, red nacional, departamental, vecinal y proporción pavimentada.

**Llave de cruce:** `DEPARTAMENTO`.

In [13]:
mtc_dep_raw = pd.read_excel(PATHS["mtc_departamento"], sheet_name="2025", header=None)
print(f"MTC infraestructura departamental raw: {mtc_dep_raw.shape[0]:,} filas x {mtc_dep_raw.shape[1]} columnas")
mtc_dep_raw.head(20)

MTC infraestructura departamental raw: 39 filas x 15 columnas

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"Infraestructura Vial Existente del SINAC, seg...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,(Clasificador de Rutas D.S.011-2016-MTC al 31 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Kilómetros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,DEPARTAMENTO,LONGITUD \nTOTAL,NaN,NACIONAL,NaN,NaN,NaN,DEPARTAMENTAL 1/,NaN,NaN,NaN,VECINAL 2/,NaN,NaN
7,NaN,NaN,NaN,NaN,SUB TOTAL,Pavimentada,No Pavimentada,NaN,SUB-TOTAL,Pavimento,No Pavimentada,NaN,SUB-TOTAL,Pavimento,No Pavimentada
8,NaN,TOTAL,176936.349875,NaN,27679.789,22875.143,4804.646,NaN,27828.458,7700.215,20128.243,NaN,121428.102875,3944.96,117483.142875
9,NaN,Amazonas,3903.732,NaN,1155.121,849.877,305.244,NaN,585.018,51.15,533.868,NaN,2163.593,42.564,2121.029
10,NaN,Áncash,10767.648,NaN,1885.063,1436.347,448.716,NaN,1222.721,525.068,697.653,NaN,7659.864,138.928,7520.936
11,NaN,Apurímac,8358.971,NaN,1282.451,1049.536,232.915,NaN,1298.097,302.278,995.819,NaN,5778.423,80.869,5697.554
12,NaN,Arequipa,10322.272,NaN,1495.236,1271.374,223.862,NaN,1749.739,1009.355,740.384,NaN,7077.297,605.866,6471.431
13,NaN,Ayacucho,12678.733,NaN,1805.074,1706.34,98.734,NaN,1774.034,633.729,1140.305,NaN,9099.625,145.306,8954.319
14,NaN,Cajamarca,15935.565012,NaN,1733.925,1543.988,189.937,NaN,935.692,97.379,838.313,NaN,13265.948012,358.8,12907.148012
15,NaN,Callao,51.586,NaN,44.687,44.687,0,NaN,6.899,5.151,1.748,NaN,0,0,0
16,NaN,Cusco,17779.135,NaN,2097.371,1665.141,432.23,NaN,2863.123,864.463,1998.66,NaN,12818.641,349.109,12469.532
17,NaN,Huancavelica,8511.426,NaN,1445.393,1191.902,253.491,NaN,2008.516,570.501,1438.015,NaN,5057.517,117.176,4940.341
18,NaN,Huánuco,8209.057,NaN,1333.478,929.597,403.881,NaN,791.977,28.882,763.095,NaN,6083.602,101.38,5982.222
19,NaN,Ica,3721.461,NaN,698.186,696.092,2.094,NaN,744.866,214.672,530.194,NaN,2278.409,192.139,2086.27

In [14]:
cols_excel = [1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]
mtc_dep = mtc_dep_raw.iloc[9:, cols_excel].copy()
mtc_dep.columns = [
    "DEPARTAMENTO_MTC_DEP", "MTC_DEP_RED_TOTAL_KM", "MTC_DEP_NACIONAL_TOTAL_KM",
    "MTC_DEP_NACIONAL_PAV_KM", "MTC_DEP_NACIONAL_NO_PAV_KM",
    "MTC_DEP_DEPARTAMENTAL_TOTAL_KM", "MTC_DEP_DEPARTAMENTAL_PAV_KM", "MTC_DEP_DEPARTAMENTAL_NO_PAV_KM",
    "MTC_DEP_VECINAL_TOTAL_KM", "MTC_DEP_VECINAL_PAV_KM", "MTC_DEP_VECINAL_NO_PAV_KM",
]
mtc_dep = mtc_dep.dropna(subset=["DEPARTAMENTO_MTC_DEP"]).copy()
mtc_dep = mtc_dep[~mtc_dep["DEPARTAMENTO_MTC_DEP"].astype(str).str.upper().str.contains("FUENTE|ELABORACION|ELABORACIÓN|NOTA", na=False)].copy()
mtc_dep["_DEP_NORM"] = mtc_dep["DEPARTAMENTO_MTC_DEP"].apply(normalizar_texto)

cols_mtc_dep = [c for c in mtc_dep.columns if c.startswith("MTC_DEP_")]
for col in cols_mtc_dep:
    mtc_dep[col] = pd.to_numeric(mtc_dep[col], errors="coerce")

mtc_dep["MTC_DEP_PAV_TOTAL_KM"] = mtc_dep["MTC_DEP_NACIONAL_PAV_KM"] + mtc_dep["MTC_DEP_DEPARTAMENTAL_PAV_KM"] + mtc_dep["MTC_DEP_VECINAL_PAV_KM"]
mtc_dep["MTC_DEP_NO_PAV_TOTAL_KM"] = mtc_dep["MTC_DEP_NACIONAL_NO_PAV_KM"] + mtc_dep["MTC_DEP_DEPARTAMENTAL_NO_PAV_KM"] + mtc_dep["MTC_DEP_VECINAL_NO_PAV_KM"]
mtc_dep["MTC_DEP_PCT_PAVIMENTADA"] = np.where(
    mtc_dep["MTC_DEP_RED_TOTAL_KM"] > 0,
    mtc_dep["MTC_DEP_PAV_TOTAL_KM"] / mtc_dep["MTC_DEP_RED_TOTAL_KM"] * 100,
    np.nan,
)
cols_mtc_dep_final = [
    "MTC_DEP_RED_TOTAL_KM", "MTC_DEP_NACIONAL_TOTAL_KM", "MTC_DEP_DEPARTAMENTAL_TOTAL_KM",
    "MTC_DEP_VECINAL_TOTAL_KM", "MTC_DEP_PAV_TOTAL_KM", "MTC_DEP_NO_PAV_TOTAL_KM",
    "MTC_DEP_PCT_PAVIMENTADA",
]
mtc_dep_sel = mtc_dep[["_DEP_NORM"] + cols_mtc_dep_final].drop_duplicates("_DEP_NORM")

assert mtc_dep_sel["_DEP_NORM"].duplicated().sum() == 0, "MTC departamental tiene llaves duplicadas."
print(f"Departamentos MTC 2025: {mtc_dep_sel.shape[0]}")
mtc_dep_sel.head()

Departamentos MTC 2025: 27

,_DEP_NORM,MTC_DEP_RED_TOTAL_KM,MTC_DEP_NACIONAL_TOTAL_KM,MTC_DEP_DEPARTAMENTAL_TOTAL_KM,MTC_DEP_VECINAL_TOTAL_KM,MTC_DEP_PAV_TOTAL_KM,MTC_DEP_NO_PAV_TOTAL_KM,MTC_DEP_PCT_PAVIMENTADA
9,AMAZONAS,3903.732,1155.121,585.018,2163.593,943.591,2960.141,24.171511
10,ANCASH,10767.648,1885.063,1222.721,7659.864,2100.343,8667.305,19.506052
11,APURIMAC,8358.971,1282.451,1298.097,5778.423,1432.683,6926.288,17.139466
12,AREQUIPA,10322.272,1495.236,1749.739,7077.297,2886.595,7435.677,27.964725
13,AYACUCHO,12678.733,1805.074,1774.034,9099.625,2485.375,10193.358,19.602708

In [15]:
df_antes = df.copy()
df = df.merge(mtc_dep_sel, on="_DEP_NORM", how="left", validate="many_to_one")
cov_mtc_dep, cruz_mtc_dep, no_mtc_dep, nulos_mtc_dep = validar_merge(
    df_antes, df, "MTC infraestructura vial por departamento 2025", cols_mtc_dep_final, llave="CODIGO_SINIESTRO"
)

print("\nEjemplos sin cruce MTC departamento:")
df.loc[df["MTC_DEP_RED_TOTAL_KM"].isna(), ["DEPARTAMENTO"]].drop_duplicates().head(10)

================================================================================
VALIDACIÓN POST-MERGE: MTC infraestructura vial por departamento 2025
================================================================================
Filas antes:   9,106
Filas después: 9,106
Duplicados en llave CODIGO_SINIESTRO: 0
Cobertura fuente: 100.00% (9,106 cruzados; 0 no cruzados)
Columnas nuevas: 7

% de nulos en variables nuevas:

                         variable  nulos  nulos_pct
0            MTC_DEP_RED_TOTAL_KM      0        0.0
1       MTC_DEP_NACIONAL_TOTAL_KM      0        0.0
2  MTC_DEP_DEPARTAMENTAL_TOTAL_KM      0        0.0
3        MTC_DEP_VECINAL_TOTAL_KM      0        0.0
4            MTC_DEP_PAV_TOTAL_KM      0        0.0
5         MTC_DEP_NO_PAV_TOTAL_KM      0        0.0
6         MTC_DEP_PCT_PAVIMENTADA      0        0.0

Ejemplos sin cruce MTC departamento:

Empty DataFrame
Columns: [DEPARTAMENTO]
Index: []

## 5. Fuentes relacionales ONSV: personas y vehículos involucrados

Además de fuentes externas, se integran dos bases relacionales oficiales de ONSV: personas involucradas y vehículos involucrados.

Estas bases no se pueden cruzar directamente fila por fila porque un siniestro puede tener varias personas y varios vehículos. Por eso primero se agregan por `CODIGO_SINIESTRO`, generando una sola fila resumen por siniestro.

Para evitar fuga de información, no se usan como variables predictoras `GRAVEDAD`, `LUGAR ATENCIÓN LESIONADO`, `LUGAR DE DEFUNCIÓN` ni conteos directos de fallecidos o lesionados derivados de personas.

In [16]:
personas = leer_excel_onsv(PATHS["personas_raw"], sheet_name="PERSONAS INVOLUCRADAS")
vehiculos = leer_excel_onsv(PATHS["vehiculos_raw"], sheet_name="VEHICULO INVOLUCRADOS")

print(f"Personas involucradas: {personas.shape[0]:,} filas x {personas.shape[1]} columnas")
print(f"Vehículos involucrados: {vehiculos.shape[0]:,} filas x {vehiculos.shape[1]} columnas")

Personas involucradas: 25,412 filas x 32 columnas
Vehículos involucrados: 12,667 filas x 25 columnas

In [17]:
def validar_unicidad_por_siniestro(df_agg, nombre):
    duplicados = int(df_agg["CODIGO_SINIESTRO"].duplicated().sum())
    assert duplicados == 0, f"{nombre} tiene CODIGO_SINIESTRO duplicado después de agrupar."
    print(f"{nombre}: {df_agg.shape[0]:,} siniestros únicos; duplicados={duplicados}")


def crear_agregados_personas(personas_df):
    col_codigo = buscar_columna(personas_df, "CODIGO SINIESTRO")
    col_tipo = buscar_columna(personas_df, "TIPO PERSONA")
    col_edad = buscar_columna(personas_df, "EDAD")
    col_sexo = buscar_columna(personas_df, "SEXO")
    col_estado_lic = buscar_columna(personas_df, "ESTADO LICENCIA")
    col_dosaje = buscar_columna(personas_df, "RESULTADO DEL DOSAJE ETILICO CUALITATIVO")

    tmp = personas_df.copy()
    tmp["CODIGO_SINIESTRO"] = tmp[col_codigo].astype(str)
    tmp["_TIPO_N"] = tmp[col_tipo].apply(normalizar_texto)
    tmp["_SEXO_N"] = tmp[col_sexo].apply(normalizar_texto)
    tmp["_ESTADO_LIC_N"] = tmp[col_estado_lic].apply(normalizar_texto)
    tmp["_DOSAJE_N"] = tmp[col_dosaje].apply(normalizar_texto)
    tmp["_EDAD_NUM"] = pd.to_numeric(tmp[col_edad], errors="coerce")

    es_conductor = tmp["_TIPO_N"].str.contains("CONDUCTOR", na=False)
    es_conductor_fugado = tmp["_TIPO_N"].str.contains("CONDUCTOR FUGADO", na=False)
    es_peaton = tmp["_TIPO_N"].str.contains("PEATON", na=False)
    es_pasajero_ocupante = tmp["_TIPO_N"].str.contains("PASAJERO|OCUPANTE", na=False)
    lic_problema = tmp["_ESTADO_LIC_N"].str.contains("SIN LICENCIA|VENCID|SUSPEND|CANCEL|NO VIGENTE", na=False)
    dosaje_pos = tmp["_DOSAJE_N"].str.contains("POSITIVO", na=False)
    dosaje_eval = tmp["_DOSAJE_N"].isin(["POSITIVO", "NEGATIVO"])
    sexo_masc = tmp["_SEXO_N"].eq("MASCULINO")

    base = pd.DataFrame({"CODIGO_SINIESTRO": tmp["CODIGO_SINIESTRO"].dropna().unique()})
    g = tmp.groupby("CODIGO_SINIESTRO")
    agg = base.set_index("CODIGO_SINIESTRO")
    agg["PER_TOTAL_PERSONAS"] = g.size()
    agg["PER_N_CONDUCTORES"] = tmp[es_conductor].groupby("CODIGO_SINIESTRO").size()
    agg["PER_N_CONDUCTORES_FUGADOS"] = tmp[es_conductor_fugado].groupby("CODIGO_SINIESTRO").size()
    agg["PER_N_PEATONES"] = tmp[es_peaton].groupby("CODIGO_SINIESTRO").size()
    agg["PER_N_PASAJEROS_OCUPANTES"] = tmp[es_pasajero_ocupante].groupby("CODIGO_SINIESTRO").size()
    conductores = tmp[es_conductor].copy()
    agg["PER_EDAD_COND_PROM"] = conductores.groupby("CODIGO_SINIESTRO")["_EDAD_NUM"].mean()
    agg["PER_EDAD_COND_MIN"] = conductores.groupby("CODIGO_SINIESTRO")["_EDAD_NUM"].min()
    agg["PER_EDAD_COND_MAX"] = conductores.groupby("CODIGO_SINIESTRO")["_EDAD_NUM"].max()
    agg["PER_ANY_COND_MASCULINO"] = sexo_masc[es_conductor].groupby(tmp.loc[es_conductor, "CODIGO_SINIESTRO"]).max().astype(float)
    agg["PER_ANY_LIC_PROBLEMA"] = lic_problema[es_conductor].groupby(tmp.loc[es_conductor, "CODIGO_SINIESTRO"]).max().astype(float)
    agg["PER_ANY_DOSAJE_POS"] = dosaje_pos[es_conductor].groupby(tmp.loc[es_conductor, "CODIGO_SINIESTRO"]).max().astype(float)
    agg["PER_ANY_DOSAJE_EVALUADO"] = dosaje_eval[es_conductor].groupby(tmp.loc[es_conductor, "CODIGO_SINIESTRO"]).max().astype(float)
    cols_count = ["PER_N_CONDUCTORES", "PER_N_CONDUCTORES_FUGADOS", "PER_N_PEATONES", "PER_N_PASAJEROS_OCUPANTES"]
    agg[cols_count] = agg[cols_count].fillna(0).astype(int)
    agg = agg.reset_index()
    validar_unicidad_por_siniestro(agg, "personas_agg")
    return agg


def crear_agregados_vehiculos(vehiculos_df):
    col_codigo = buscar_columna(vehiculos_df, "CODIGO SINIESTRO")
    col_situacion = buscar_columna(vehiculos_df, "SITUACION VEHICULO")
    col_modalidad = buscar_columna(vehiculos_df, "MODALIDAD DE TRANSPORTE")
    col_estado_soat = buscar_columna(vehiculos_df, "ESTADO SOAT")
    col_estado_citv = buscar_columna(vehiculos_df, "ESTADO CITV")
    col_posee_seguro = buscar_columna(vehiculos_df, "POSEE SEGURO")
    col_vehiculo = buscar_columna(vehiculos_df, "VEHICULO")

    tmp = vehiculos_df.copy()
    tmp["CODIGO_SINIESTRO"] = tmp[col_codigo].astype(str)
    tmp["_SITUACION_N"] = tmp[col_situacion].apply(normalizar_texto)
    tmp["_MODALIDAD_N"] = tmp[col_modalidad].apply(normalizar_texto)
    tmp["_SOAT_N"] = tmp[col_estado_soat].apply(normalizar_texto)
    tmp["_CITV_N"] = tmp[col_estado_citv].apply(normalizar_texto)
    tmp["_POSEE_SEGURO_N"] = tmp[col_posee_seguro].apply(normalizar_texto)
    tmp["_VEHICULO_N"] = tmp[col_vehiculo].apply(normalizar_texto)

    fugado = tmp["_SITUACION_N"].str.contains("FUGADO", na=False)
    carga = tmp["_MODALIDAD_N"].str.contains("CARGA", na=False)
    publico = tmp["_MODALIDAD_N"].str.contains("PUBLICO|PASAJER|REGULAR", na=False)
    particular = tmp["_MODALIDAD_N"].str.contains("PARTICULAR", na=False)
    moto = tmp["_VEHICULO_N"].str.contains("MOTO|TRIMOTO|SCOOTER", na=False)
    auto = tmp["_VEHICULO_N"].str.contains("AUTOMOVIL|STATION WAGON", na=False)
    camion_bus = tmp["_VEHICULO_N"].str.contains("CAMION|OMNIBUS|BUS|REMOLCADOR|SEMIREMOLQUE", na=False)
    soat_problema = tmp["_SOAT_N"].str.contains("NO REGISTRA|VENCID|NO TIENE|SIN", na=False)
    citv_problema = tmp["_CITV_N"].str.contains("NO REGISTRA|VENCID|NO TIENE|SIN", na=False)
    seguro_problema = tmp["_POSEE_SEGURO_N"].str.contains("NO|NO ESPECIFICA", na=False)

    base = pd.DataFrame({"CODIGO_SINIESTRO": tmp["CODIGO_SINIESTRO"].dropna().unique()})
    g = tmp.groupby("CODIGO_SINIESTRO")
    agg = base.set_index("CODIGO_SINIESTRO")
    agg["VEH_TOTAL"] = g.size()
    agg["VEH_N_FUGADOS"] = tmp[fugado].groupby("CODIGO_SINIESTRO").size()
    agg["VEH_ANY_FUGADO"] = fugado.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_CARGA"] = carga.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_PUBLICO"] = publico.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_PARTICULAR"] = particular.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_MOTO"] = moto.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_AUTO"] = auto.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_CAMION_BUS"] = camion_bus.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_SOAT_PROBLEMA"] = soat_problema.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_CITV_PROBLEMA"] = citv_problema.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_ANY_SEGURO_PROBLEMA"] = seguro_problema.groupby(tmp["CODIGO_SINIESTRO"]).max().astype(float)
    agg["VEH_N_FUGADOS"] = agg["VEH_N_FUGADOS"].fillna(0).astype(int)
    agg = agg.reset_index()
    validar_unicidad_por_siniestro(agg, "vehiculos_agg")
    return agg

In [18]:
personas_agg = crear_agregados_personas(personas)
vehiculos_agg = crear_agregados_vehiculos(vehiculos)

print("Cobertura de llaves antes del merge:")
llaves_base = set(df["CODIGO_SINIESTRO"].astype(str))
llaves_personas = set(personas_agg["CODIGO_SINIESTRO"].astype(str))
llaves_vehiculos = set(vehiculos_agg["CODIGO_SINIESTRO"].astype(str))
print(f"Base:      {len(llaves_base):,} siniestros")
print(f"Personas:  {len(llaves_personas):,} siniestros ({len(llaves_base & llaves_personas) / len(llaves_base) * 100:.2f}% cobertura)")
print(f"Vehículos: {len(llaves_vehiculos):,} siniestros ({len(llaves_base & llaves_vehiculos) / len(llaves_base) * 100:.2f}% cobertura)")
assert llaves_base.issubset(llaves_personas), "Hay siniestros de la base que no aparecen en PERSONAS."
assert llaves_base.issubset(llaves_vehiculos), "Hay siniestros de la base que no aparecen en VEHICULOS."

personas_agg: 9,106 siniestros únicos; duplicados=0
vehiculos_agg: 9,106 siniestros únicos; duplicados=0
Cobertura de llaves antes del merge:
Base:      9,106 siniestros
Personas:  9,106 siniestros (100.00% cobertura)
Vehículos: 9,106 siniestros (100.00% cobertura)

In [19]:
cols_personas = [c for c in personas_agg.columns if c != "CODIGO_SINIESTRO"]
df_antes = df.copy()
df = df.merge(personas_agg, on="CODIGO_SINIESTRO", how="left", validate="one_to_one")
cov_personas, cruz_personas, no_personas, nulos_personas = validar_merge(
    df_antes, df, "ONSV personas involucradas 2021-2025", cols_personas, llave="CODIGO_SINIESTRO"
)

================================================================================
VALIDACIÓN POST-MERGE: ONSV personas involucradas 2021-2025
================================================================================
Filas antes:   9,106
Filas después: 9,106
Duplicados en llave CODIGO_SINIESTRO: 0
Cobertura fuente: 100.00% (9,106 cruzados; 0 no cruzados)
Columnas nuevas: 12

% de nulos en variables nuevas:

                     variable  nulos  nulos_pct
6           PER_EDAD_COND_MIN   1126      12.37
7           PER_EDAD_COND_MAX   1126      12.37
5          PER_EDAD_COND_PROM   1126      12.37
8      PER_ANY_COND_MASCULINO     53       0.58
10         PER_ANY_DOSAJE_POS     53       0.58
9        PER_ANY_LIC_PROBLEMA     53       0.58
11    PER_ANY_DOSAJE_EVALUADO     53       0.58
0          PER_TOTAL_PERSONAS      0       0.00
3              PER_N_PEATONES      0       0.00
2   PER_N_CONDUCTORES_FUGADOS      0       0.00
1           PER_N_CONDUCTORES      0       0.00
4   PER_N_PASAJEROS_OCUPANTES      0       0.00

In [20]:
cols_vehiculos = [c for c in vehiculos_agg.columns if c != "CODIGO_SINIESTRO"]
df_antes = df.copy()
df = df.merge(vehiculos_agg, on="CODIGO_SINIESTRO", how="left", validate="one_to_one")
cov_vehiculos, cruz_vehiculos, no_vehiculos, nulos_vehiculos = validar_merge(
    df_antes, df, "ONSV vehículos involucrados 2021-2025", cols_vehiculos, llave="CODIGO_SINIESTRO"
)

================================================================================
VALIDACIÓN POST-MERGE: ONSV vehículos involucrados 2021-2025
================================================================================
Filas antes:   9,106
Filas después: 9,106
Duplicados en llave CODIGO_SINIESTRO: 0
Cobertura fuente: 100.00% (9,106 cruzados; 0 no cruzados)
Columnas nuevas: 12

% de nulos en variables nuevas:

                   variable  nulos  nulos_pct
0                 VEH_TOTAL      0        0.0
1             VEH_N_FUGADOS      0        0.0
2            VEH_ANY_FUGADO      0        0.0
3             VEH_ANY_CARGA      0        0.0
4           VEH_ANY_PUBLICO      0        0.0
5        VEH_ANY_PARTICULAR      0        0.0
6              VEH_ANY_MOTO      0        0.0
7              VEH_ANY_AUTO      0        0.0
8        VEH_ANY_CAMION_BUS      0        0.0
9     VEH_ANY_SOAT_PROBLEMA      0        0.0
10    VEH_ANY_CITV_PROBLEMA      0        0.0
11  VEH_ANY_SEGURO_PROBLEMA      0        0.0

## 6. Fuentes evaluadas y no integradas en esta versión

- **INEI / EstaDist:** se evaluó para indicadores distritales, pero el portal requiere selección manual de distritos para exportación.
- **SENAMHI:** se evaluó para clima objetivo, pero requiere descarga por estación y cruce espaciotemporal por coordenadas y fecha exacta.
- **MTC flujo vehicular por peajes:** útil como proxy de exposición vehicular, pero su cruce correcto requiere peajes georreferenciados o agregación por ruta/departamento.

## 7. Trazabilidad de variables añadidas

Se documenta cada variable nueva con fuente, archivo origen, URL, llave de cruce, año del dato, nivel geográfico, cobertura y observaciones metodológicas.

In [21]:
trazabilidad = []

agregar_trazabilidad(
    trazabilidad, cols_mtc_rvn,
    fuente="MTC - Red Vial Nacional SINAC 2022-2025",
    archivo_origen=PATHS["mtc_rvn"],
    url="https://www.datosabiertos.gob.pe/dataset/red-vial-nacional-del-sistema-nacional-de-carreteras-2022-2025-ministerio-de-transportes-y-comunicaciones-mtc",
    llave_cruce="COD CARRETERA -> CODIGO_RUTA",
    anio_dato="2022-2025",
    nivel_geografico="Ruta / tramo agregado por código de ruta",
    cobertura=cov_mtc_rvn,
    cruzados=cruz_mtc_rvn,
    no_cruzados=no_mtc_rvn,
    observaciones="Cobertura parcial esperada: no aplica a vías urbanas, NO CORRESPONDE, SIN CLASIFICAR o rutas no nacionales.",
)

agregar_trazabilidad(
    trazabilidad, cols_idh_merge,
    fuente="PNUD/IPE - IDH y componentes 2019",
    archivo_origen=PATHS["idh"],
    url="https://ipe.org.pe/indice-de-desarrollo-humano-idh/",
    llave_cruce="DEPARTAMENTO + PROVINCIA + DISTRITO",
    anio_dato="2019",
    nivel_geografico="Distrito",
    cobertura=cov_idh,
    cruzados=cruz_idh,
    no_cruzados=no_idh,
    observaciones="Indicador estructural previo al periodo 2021-2025; puede haber no cruces por diferencias de nomenclatura distrital.",
)

agregar_trazabilidad(
    trazabilidad, cols_mtc_dep_final,
    fuente="MTC - Infraestructura vial existente del SINAC por departamento",
    archivo_origen=PATHS["mtc_departamento"],
    url="https://www.gob.pe/institucion/mtc/informes-publicaciones/344790-estadistica-infraestructura-de-transportes-infraestructura-vial",
    llave_cruce="DEPARTAMENTO",
    anio_dato="2025 (junio)",
    nivel_geografico="Departamento",
    cobertura=cov_mtc_dep,
    cruzados=cruz_mtc_dep,
    no_cruzados=no_mtc_dep,
    observaciones="Variables agregadas a nivel departamental; no capturan heterogeneidad intradepartamental.",
)

agregar_trazabilidad(
    trazabilidad, cols_personas,
    fuente="ONSV - Personas involucradas en siniestros fatales 2021-2025",
    archivo_origen=PATHS["personas_raw"],
    url="Fuente oficial ONSV compartida por el grupo",
    llave_cruce="CODIGO_SINIESTRO",
    anio_dato="2021-2025 preliminar",
    nivel_geografico="Siniestro, agregado desde personas involucradas",
    cobertura=cov_personas,
    cruzados=cruz_personas,
    no_cruzados=no_personas,
    observaciones="Variables agregadas por siniestro. Se excluyen gravedad, lugar de atención y lugar de defunción para evitar fuga de información.",
)

agregar_trazabilidad(
    trazabilidad, cols_vehiculos,
    fuente="ONSV - Vehículos involucrados en siniestros fatales 2021-2025",
    archivo_origen=PATHS["vehiculos_raw"],
    url="Fuente oficial ONSV compartida por el grupo",
    llave_cruce="CODIGO_SINIESTRO",
    anio_dato="2021-2025 preliminar",
    nivel_geografico="Siniestro, agregado desde vehículos involucrados",
    cobertura=cov_vehiculos,
    cruzados=cruz_vehiculos,
    no_cruzados=no_vehiculos,
    observaciones="Variables agregadas por siniestro: cantidad, modalidad, tipo de vehículo, SOAT, CITV, seguro y fuga.",
)

df_trazabilidad = pd.DataFrame(trazabilidad)
df_trazabilidad

,variable,fuente,archivo_origen,url_fuente,llave_cruce,anio_dato,nivel_geografico,cobertura_pct,registros_cruzados,registros_no_cruzados,observaciones
0,MTC_RVN_LONGITUD_KM,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
1,MTC_RVN_N_CARRILES_MEDIANA,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
2,MTC_RVN_SUPERFICIE_DOMINANTE,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
3,MTC_RVN_ESTADO_DOMINANTE,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
4,MTC_RVN_ES_CONCESIONADA,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
5,MTC_RVN_CONCESION_PRINCIPAL,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
6,MTC_RVN_CORREDOR_LOGISTICO,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
7,MTC_RVN_N_TRAMOS,MTC - Red Vial Nacional SINAC 2022-2025,/home/node-vault07/projects/siniestros-fatales...,https://www.datosabiertos.gob.pe/dataset/red-v...,COD CARRETERA -> CODIGO_RUTA,2022-2025,Ruta / tramo agregado por código de ruta,55.04,5012,4094,Cobertura parcial esperada: no aplica a vías u...
8,IDH_UBIGEO,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
9,IDH_2019,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
10,IDH_ESP_VIDA_2019,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
11,IDH_EDUC_SECUND_PCT_2019,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
12,IDH_ANIOS_EDUC_2019,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
13,IDH_INGRESO_PERCAP_2019,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
14,IDH_POBLACION_2019,PNUD/IPE - IDH y componentes 2019,/home/node-vault07/projects/siniestros-fatales...,https://ipe.org.pe/indice-de-desarrollo-humano...,DEPARTAMENTO + PROVINCIA + DISTRITO,2019,Distrito,96.91,8825,281,Indicador estructural previo al periodo 2021-2...
15,MTC_DEP_RED_TOTAL_KM,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
16,MTC_DEP_NACIONAL_TOTAL_KM,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
17,MTC_DEP_DEPARTAMENTAL_TOTAL_KM,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
18,MTC_DEP_VECINAL_TOTAL_KM,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
19,MTC_DEP_PAV_TOTAL_KM,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
20,MTC_DEP_NO_PAV_TOTAL_KM,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
21,MTC_DEP_PCT_PAVIMENTADA,MTC - Infraestructura vial existente del SINAC...,/home/node-vault07/projects/siniestros-fatales...,https://www.gob.pe/institucion/mtc/informes-pu...,DEPARTAMENTO,2025 (junio),Departamento,100.00,9106,0,Variables agregadas a nivel departamental; no ...
22,PER_TOTAL_PERSONAS,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
23,PER_N_CONDUCTORES,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
24,PER_N_CONDUCTORES_FUGADOS,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
25,PER_N_PEATONES,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
26,PER_N_PASAJEROS_OCUPANTES,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
27,PER_EDAD_COND_PROM,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
28,PER_EDAD_COND_MIN,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
29,PER_EDAD_COND_MAX,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
30,PER_ANY_COND_MASCULINO,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
31,PER_ANY_LIC_PROBLEMA,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
32,PER_ANY_DOSAJE_POS,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
33,PER_ANY_DOSAJE_EVALUADO,ONSV - Personas involucradas en siniestros fat...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde personas involucradas",100.00,9106,0,Variables agregadas por siniestro. Se excluyen...
34,VEH_TOTAL,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
35,VEH_N_FUGADOS,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
36,VEH_ANY_FUGADO,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
37,VEH_ANY_CARGA,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
38,VEH_ANY_PUBLICO,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
39,VEH_ANY_PARTICULAR,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
40,VEH_ANY_MOTO,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
41,VEH_ANY_AUTO,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
42,VEH_ANY_CAMION_BUS,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
43,VEH_ANY_SOAT_PROBLEMA,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
44,VEH_ANY_CITV_PROBLEMA,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."
45,VEH_ANY_SEGURO_PROBLEMA,ONSV - Vehículos involucrados en siniestros fa...,/home/node-vault07/projects/siniestros-fatales...,Fuente oficial ONSV compartida por el grupo,CODIGO_SINIESTRO,2021-2025 preliminar,"Siniestro, agregado desde vehículos involucrados",100.00,9106,0,"Variables agregadas por siniestro: cantidad, m..."

## 8. Validación global y exportación

Antes de exportar se verifica que no se hayan perdido filas, que no existan duplicados en `CODIGO_SINIESTRO`, que la variable objetivo no cambie y que los archivos de salida queden en UTF-8 con BOM (`utf-8-sig`) para evitar problemas de tildes en Excel.

In [22]:
cols_aux = [c for c in df.columns if c.startswith("_")]
df_final = df.drop(columns=cols_aux, errors="ignore").copy()

assert len(df_final) == filas_originales, "La cantidad de filas cambió durante el enriquecimiento."
assert df_final["CODIGO_SINIESTRO"].duplicated().sum() == 0, "Hay CODIGO_SINIESTRO duplicados en la salida final."

cols_nuevas_enriquecimiento = [c for c in df_final.columns if c not in cols_originales]
nulos_todas_nuevas = reporte_nulos_nuevos(df_final, cols_nuevas_enriquecimiento)

print("=" * 80)
print("VALIDACIÓN GLOBAL FINAL")
print("=" * 80)
print(f"Filas del limpio original:        {filas_originales:,}")
print(f"Filas finales enriquecidas:       {len(df_final):,}")
print(f"Duplicados CODIGO_SINIESTRO:      {int(df_final['CODIGO_SINIESTRO'].duplicated().sum()):,}")
print(f"Columnas del limpio original:     {len(columnas_limpio_originales)}")
print(f"Columnas base para enriquecer:    {len(cols_originales)}")
print(f"Variables nuevas enriquecimiento: {len(cols_nuevas_enriquecimiento)}")
print(f"Columnas finales:                 {df_final.shape[1]}")
print("\nNulos en variables nuevas de enriquecimiento:")
display(nulos_todas_nuevas)

df_final.to_csv(PATHS["salida_enriquecido"], index=False, encoding="utf-8-sig")
df_trazabilidad.to_csv(PATHS["salida_trazabilidad"], index=False, encoding="utf-8-sig")

print("\nArchivos generados:")
print(PATHS["salida_enriquecido"])
print(PATHS["salida_trazabilidad"])

================================================================================
VALIDACIÓN GLOBAL FINAL
================================================================================
Filas del limpio original:        9,106
Filas finales enriquecidas:       9,106
Duplicados CODIGO_SINIESTRO:      0
Columnas del limpio original:     27
Columnas base para enriquecer:    27
Variables nuevas enriquecimiento: 46
Columnas finales:                 73

Nulos en variables nuevas de enriquecimiento:

                          variable  nulos  nulos_pct
0              MTC_RVN_LONGITUD_KM   4094      44.96
1       MTC_RVN_N_CARRILES_MEDIANA   4094      44.96
2     MTC_RVN_SUPERFICIE_DOMINANTE   4094      44.96
3         MTC_RVN_ESTADO_DOMINANTE   4094      44.96
4          MTC_RVN_ES_CONCESIONADA   4094      44.96
5      MTC_RVN_CONCESION_PRINCIPAL   4094      44.96
6       MTC_RVN_CORREDOR_LOGISTICO   4094      44.96
7                 MTC_RVN_N_TRAMOS   4094      44.96
27              PER_EDAD_COND_PROM   1126      12.37
29               PER_EDAD_COND_MAX   1126      12.37
28               PER_EDAD_COND_MIN   1126      12.37
10               IDH_ESP_VIDA_2019    281       3.09
8                       IDH_UBIGEO    281       3.09
9                         IDH_2019    281       3.09
13         IDH_INGRESO_PERCAP_2019    281       3.09
12             IDH_ANIOS_EDUC_2019    281       3.09
11        IDH_EDUC_SECUND_PCT_2019    281       3.09
14              IDH_POBLACION_2019    281       3.09
33         PER_ANY_DOSAJE_EVALUADO     53       0.58
32              PER_ANY_DOSAJE_POS     53       0.58
31            PER_ANY_LIC_PROBLEMA     53       0.58
30          PER_ANY_COND_MASCULINO     53       0.58
21         MTC_DEP_PCT_PAVIMENTADA      0       0.00
20         MTC_DEP_NO_PAV_TOTAL_KM      0       0.00
19            MTC_DEP_PAV_TOTAL_KM      0       0.00
22              PER_TOTAL_PERSONAS      0       0.00
18        MTC_DEP_VECINAL_TOTAL_KM      0       0.00
15            MTC_DEP_RED_TOTAL_KM      0       0.00
16       MTC_DEP_NACIONAL_TOTAL_KM      0       0.00
17  MTC_DEP_DEPARTAMENTAL_TOTAL_KM      0       0.00
26       PER_N_PASAJEROS_OCUPANTES      0       0.00
23               PER_N_CONDUCTORES      0       0.00
24       PER_N_CONDUCTORES_FUGADOS      0       0.00
25                  PER_N_PEATONES      0       0.00
34                       VEH_TOTAL      0       0.00
35                   VEH_N_FUGADOS      0       0.00
36                  VEH_ANY_FUGADO      0       0.00
37                   VEH_ANY_CARGA      0       0.00
38                 VEH_ANY_PUBLICO      0       0.00
39              VEH_ANY_PARTICULAR      0       0.00
40                    VEH_ANY_MOTO      0       0.00
41                    VEH_ANY_AUTO      0       0.00
42              VEH_ANY_CAMION_BUS      0       0.00
43           VEH_ANY_SOAT_PROBLEMA      0       0.00
44           VEH_ANY_CITV_PROBLEMA      0       0.00
45         VEH_ANY_SEGURO_PROBLEMA      0       0.00

Archivos generados:
/home/node-vault07/projects/siniestros-fatales-peru-ml/data/procesada/siniestros_enriquecido.csv
/home/node-vault07/projects/siniestros-fatales-peru-ml/data/procesada/trazabilidad_variables_externas.csv

In [23]:
for salida in [PATHS["salida_enriquecido"], PATHS["salida_trazabilidad"]]:
    raw = salida.read_bytes()
    assert raw.startswith(codecs.BOM_UTF8), f"{salida.name} no fue exportado con BOM UTF-8."
    _ = pd.read_csv(salida, encoding="utf-8-sig", nrows=5)
    print(f"Encoding OK: {salida.name} -> utf-8-sig, lectura validada")

print("\nPróximo paso: usar data/procesada/siniestros_enriquecido.csv como entrada del notebook 03.")

Encoding OK: siniestros_enriquecido.csv -> utf-8-sig, lectura validada
Encoding OK: trazabilidad_variables_externas.csv -> utf-8-sig, lectura validada

Próximo paso: usar data/procesada/siniestros_enriquecido.csv como entrada del notebook 03.

## 9. Resumen metodológico

El dataset enriquecido conserva las filas y columnas limpias del notebook 01 y agrega variables reales de contexto vial, territorial, humano y vehicular. Las fuentes externas aportan información del entorno donde ocurrió el siniestro; las fuentes relacionales ONSV aportan información agregada sobre personas y vehículos involucrados.

La validación de calidad del cruce incluyó: conteo de filas antes/después, duplicados de llave, consistencia de `CODIGO_SINIESTRO`, cobertura de cada fuente, porcentaje de nulos nuevos y verificación de encoding en los CSV finales.

Las variables derivadas de modelado y la variable objetivo se dejan para el notebook 03.